import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { zipSync, strToU8 } from 'fflate';
import { hubProfileVersionSchema, profileDraftSchema, hubListingSchema, dshPackageManifestSchema } from '@dsh-plugin-hub/schemas';
import { canonical } from './release.mjs';
const root = join(import.meta.dirname, '..');
const out = join(root, 'artifacts/npm');
const read = path => JSON.parse(readFileSync(path,'utf8'));
const pkg = read(join(out,'bundle/package.json'));
const pack = read(join(out,'bundle-pack.json'))[0];
const lock = read(join(root,'package-lock.json'));
const publishedAt = read(join(root,'config/preset.json')).createdAt;
dshPackageManifestSchema.parse(pkg); hubListingSchema.parse(pkg.dsh.hub);
const runtimePackage = lock.packages['node_modules/@deepseek-ai/dsh'];
const runtime = {range:runtimePackage.version,version:runtimePackage.version,integrity:runtimePackage.integrity};
const bundles = [pkg.name].map((packageName,index,names) => {
  const source = packageName === pkg.name ? pack : lock.packages['node_modules/'+packageName];
  return {packageName,selector:source.version,version:source.version,installSpec:packageName+'@'+source.version,integrity:source.integrity,sourceKind:'npm',before:[],after:index?[names[index-1]]:[]};
});
const common = {schemaVersion:1,name:'DSCODE',description:'A complete macOS DeepSeek coding TUI: persistent shell, Ultra subagents, auto approval review, Chrome MCP, Computer Use, skills, compaction, goals, hooks and session metrics.',dsh:runtime.version,runtime,bundles,patch:[],patchYaml:'[]\n',inputs:[{key:'DSH_HOME',label:'DSCODE state directory',description:'Absolute dedicated DSH home. The dscode launcher sets this automatically.',required:true,secret:false},{key:'DSH_AGENTS_HOME',label:'Isolated user skills directory',description:'The dscode launcher sets this to $DSH_HOME/agents.',required:true,secret:false},{key:'DEEPSEEK_API_KEY',label:'DeepSeek API key',description:'Optional: configure credentials with /model instead.',required:false,secret:true}]};
const unsigned = hubProfileVersionSchema.parse({...common,version:pkg.version,publishedAt,verification:{structural:'passed',composition:'local_required',activation:'local_required',platform:'darwin'}});
const release = {...unsigned,contentHash:'sha256:'+createHash('sha256').update(canonical(unsigned)).digest('hex')};
const draft=profileDraftSchema.parse({...common,slug:'dscode',visibility:'private'});
const json=x=>JSON.stringify(x,null,2)+'\n';
writeFileSync(join(out,'profile-draft.json'),json(draft));
writeFileSync(join(out,'hub-release.json'),json(release));
writeFileSync(join(out,`dscode-${pkg.version}.dshprofile`),zipSync({'release.json':strToU8(json(release)),'README.txt':strToU8('DSCODE Hub release candidate. Requires the matching npm packages to be published before public installation. No credentials included.\n')},{level:0,mtime:new Date(publishedAt)}));
const {readProfileArchive}=await import('../node_modules/@dsh-plugin-hub/cli/dist/profile-archive.js');
await readProfileArchive(join(out,`dscode-${pkg.version}.dshprofile`));
console.log(`Validated DSCODE ${pkg.version} Hub release candidate; not published.`);
