import { cpSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { replaceOnce } from './patch-util.mjs';

// DSH 0.1.5-rc.2 rewrites this empty loader root on every composition. Only
// its exact generated bytes are exempt; user config, hooks and locks stay bound.
export const generatedProfileRootHash = 'sha256:c300dcf2ebc5f02062d6591268d29d3db6fe45e0cb138f5467276fe2ba06076e';
export function patchHubDependencyReceipt(source) {
  return replaceOnce(source,
    'return (await scanProfileFiles(directory)).filter(file => configurationFile(file, hooksPresent));',
    `// dscode-hub-generated-root-v1: this empty file is produced by composition, not an install input.\n    return (await scanProfileFiles(directory)).filter(file => configurationFile(file, hooksPresent) &&\n        (hooksPresent || file.relativePath !== "cordis.yml" || file.kind !== "file" || file.hash !== "${generatedProfileRootHash}"));`);
}

export function vendorHub(source, destination) {
  const metadata = JSON.parse(readFileSync(join(source, 'package.json'), 'utf8'));
  if (metadata.version !== '0.5.0') throw Error('Review the Hub generated-root compatibility fix before upgrading Hub CLI.');
  for (const file of ['dist', 'package.json', 'LICENSE']) cpSync(join(source, file), join(destination, file), { recursive: true, filter: path => !path.endsWith('.map') && !path.endsWith('.d.ts') });
  const dependencyInstall = join(destination, 'dist/profile-dependency-install.js');
  writeFileSync(dependencyInstall, patchHubDependencyReceipt(readFileSync(dependencyInstall, 'utf8')));
  writeFileSync(join(destination, 'DSCODE_CHANGES.md'), 'Vendored @dsh-plugin-hub/cli 0.5.0 (MIT). DSCODE excludes the exact generated empty Harness cordis.yml from dependency-input receipts when no package-manager hooks are present. Other configuration and lock verification is unchanged.\n');
  return metadata.dependencies;
}
