// GENERATED by scripts/gen-whale-glyph.ts — do not edit by hand. Rerun the
// generator after changing the FishLogo path. Half-block rendering of the
// DeepSeek fish logo (figma I39:24057;88:8943 fillGeometry, exact extract;
// native 23.16x17.04 → 26 columns × 8 half-block rows).
// Blank cells are part of the glyph's fixed 26-column grid: pad, never trim.

/** Half-block whale glyph rows; render with the brand color. */
export const WHALE_GLYPH: readonly string[] = [
  '    ▄▄▄▄▄▄▄▄█    ▄█▄     ▄',
  ' ▄▄██████████▄▄  ▀███▄████',
  '▄███████████████▄  ███▀▀▀ ',
  '██     ▀▀█████▄▀██████    ',
  '██▄       ▀████▄▄████     ',
  ' ██▄        ▀██████▀      ',
  '  ▀██▄▄  ██▄  ▀███▄▄      ',
  '     ▀▀███████▀▀ ▀▀▀      ',
]

/** Fixed glyph width in terminal columns. */
export const WHALE_GLYPH_COLUMNS = 26

/** Fixed glyph height in half-block rows. */
export const WHALE_GLYPH_ROWS = 8
